### ISSUE TITLE
Need some field diagnostics

### ISSUE THREAD

**Issue by dmleman** [particle-iot/gps-ublox#8]
Hi,
Would it be possible to apply a patch (below)?
These are performance counters, which count successful GPS reports
as well as errors.
The most important error is timeout, which happens with some of our devices in the field, where logging is not available.
So, we need perf counters or something like that.
Thank you
(Note: this patch is against previous revision of your sources, if you agree in general, then I will merge with your today's changes)
diff --git a/src/ubloxGPS.cpp b/src/ubloxGPS.cpp
index 2c200c0..ef241e9 100644
--- a/src/ubloxGPS.cpp
+++ b/src/ubloxGPS.cpp
@@ -222,9 +222,21 @@ void ubloxGPS::processGPSByte(uint8_t c)
         // Loglib.info("UBX DECODE_RESULT_COMPLETE");
     }
 
+    int pos_timestamp_prev = nmea_gps.pos_timestamp;
+    int date_timestamp_prev = nmea_gps.date_timestamp;
+
     // parse NMEA message
     gps_process(&nmea_gps, &c, 1, log_enabled ? nmea_event_log_cb :  nullptr);
 
+    if(pos_timestamp_prev != nmea_gps.pos_timestamp)
+    {
+        perf_counts.pos_report_count++;
+    }
+    if(date_timestamp_prev != nmea_gps.date_timestamp) 
+    {
+        perf_counts.time_report_count++;
+    }
+
     if (getLock())
     {
         lastLockTime = Time.now() - (System.uptime() - nmea_gps.time_timestamp);
@@ -1209,6 +1221,7 @@ bool ubloxGPS::disableNMEA(void)
     err |= configMsg(UBX_CLASS_NMEA, UBX_NEMA_GST, 0) ? 0 : 0x40;
     err |= configMsg(UBX_CLASS_NMEA, UBX_NEMA_ZDA, 0) ? 0 : 0x80;
     if (err != 0) {
+        perf_counts.disable_nmea_error_count++;
         if(log_enabled) Loglib.info("disableNMEA error: 0x%02X", err);
     }
     return err == 0 ? true : false;
@@ -1279,6 +1292,7 @@ bool ubloxGPS::enableNMEA(uint8_t intervalSec, uint8_t slowIntervalSec)
     err |= configMsg(UBX_CLASS_NMEA, UBX_NEMA_ZDA, 0) ? 0 : 0x80;
 #endif
     if (err != 0) {
+        perf_counts.enable_nmea_error_count++;
         if(log_enabled) Loglib.info("enableNMEA error: 0x%02X", err);
     }
     return err == 0 ? true : false;
@@ -1292,6 +1306,7 @@ bool ubloxGPS::disablePUBX(void)
     err |= configMsg(UBX_CLASS_PUBX, UBX_PUBX_SVSTATUS, 0) ? 0 : 0x02;
     err |= configMsg(UBX_CLASS_PUBX, UBX_PUBX_TIME,     0) ? 0 : 0x04;
     if (err != 0) {
+        perf_counts.disable_pubx_error_count++;
         if(log_enabled) Loglib.info("disablePUBX error: 0x%02X", err);
     }
     return err == 0 ? true : false;
@@ -1323,6 +1338,7 @@ bool ubloxGPS::enablePUBX(uint8_t intervalSec, uint8_t slowIntervalSec)
     err |= configMsg(UBX_CLASS_PUBX, UBX_PUBX_TIME, 0) ? 0 : 0x04;
 #endif
     if (err != 0) {
+        perf_counts.enable_pubx_error_count++;
         if(log_enabled) Loglib.info("enablePUBX error: 0x%02X", err);
     }
     return err == 0 ? true : false;
@@ -1343,6 +1359,7 @@ bool ubloxGPS::disableUBX(void)
     if(log_enabled) Loglib.info("disable NAV DOP");
     err |= configMsg(UBX_CLASS_NAV, UBX_NAV_DOP, 0) ? 0 : 0x10;
     if (err != 0) {
+        perf_counts.disable_ubx_error_count++;
         if(log_enabled) Loglib.info("disableUBX error: 0x%02X", err);
     }
     return err == 0 ? true : false;
@@ -1543,6 +1560,7 @@ void ubloxGPS::waitForAckOrRsp()
         if(millis() - t0 > UBX_MSG_TIMEOUT)
         {
             rxTimeout = true;
+            perf_counts.timeouts++;
             decodeStateHandler = &ubloxGPS::stateSync1;
             if(log_enabled)
             {
diff --git a/src/ubloxGPS.h b/src/ubloxGPS.h
index 5f14e21..e32134e 100644
--- a/src/ubloxGPS.h
+++ b/src/ubloxGPS.h
@@ -816,6 +816,37 @@ public:
 
     void enableDebugNMEA(bool en);
     void hex_dump(LogLevel level, uint8_t *data, int len, Logger *logger=NULL);
+
+    typedef struct {
+        int pos_report_count {0}; //Count of PUBX POS, GPGGA, GNGGA reports
+        int time_report_count {0};//Count of PUBX TIME reports
+
+        //The following are counts of error conditions
+        int timeouts {0}; //Timeout waiting for reports
+        int enable_nmea_error_count {0};//enableNMEA failure count
+        int disable_nmea_error_count {0};//disableNMEA failure count
+        int enable_pubx_error_count {0};//enablePUBX failure count
+        int disable_pubx_error_count {0};//disablePUBX failure count
+        int disable_ubx_error_count {0};//disableUBX failure count
+
+        int getTotalErrors() const {
+            return timeouts +
+                   enable_nmea_error_count +
+                   disable_nmea_error_count +
+                   enable_pubx_error_count +
+                   disable_pubx_error_count +
+                   disable_ubx_error_count;
+        }
+        int getTotalCounts() const {
+            return getTotalErrors() +
+                pos_report_count +
+                time_report_count;
+        }
+    } perf_counts_t;
+
+    perf_counts_t getPerfCounts() const { return perf_counts; }
+    void resetPerfCounts() { perf_counts = perf_counts_t{}; }
+
 protected:
     bool checkWaitingForAckOrRspFlags() const;
 
@@ -884,6 +915,8 @@ private:
     } lib_config_t;
     lib_config_t lib_config;
 
+    perf_counts_t perf_counts;
+
     void setOn(lib_config_t &config);
     void updateGPS(void);
     void processLockStability();

**Comment by eberseth** [comment]
A PR has been created for the above patch https://github.com/particle-iot/gps-ublox/pull/10
